jobs/urls.py
from django.urls import path

from jobs import views
from jobs.views import home, publicar_vaga

app_name = 'jobs'

urlpatterns = [
    path('', home, name='home'),
    path('minhas-vagas/', views.minhas_vagas, name='minhas_vagas'),
    path('vaga/<int:vaga_id>/', views.vaga, name='vaga'),
    path('gerar-pdf/<int:vaga_id>/', views.vaga_pdf, name='vaga_pdf'),
    path('api/vagas/', views.api_listar_vagas, name='api_listar_vagas'),
    path('editar-vaga/<int:vaga_id>/', views.editar_vaga, name='editar_vaga'),
    path('publicar/', publicar_vaga, name='publicar_vaga'),

]

usuarios/urls.py
from django.contrib.auth import views
from django.urls import path

from .views import registrar, login_view

app_name = 'usuarios'

urlpatterns = [
    path('registrar/', registrar, name='registrar'),
    path('login/', login_view, name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

jobs/models.py
from django.db import models
from django.utils import timezone


# Enum para os tipos de vagas
class TipoVaga(models.TextChoices):
    TEMPO_INTEGRAL = 'TEMPO_INTEGRAL', 'Tempo integral'
    MEIO_PERIODO = 'MEIO_PERIODO', 'Meio período'
    CONTRATADO = 'CONTRATADO', 'Contratado'
    TEMPORARIO = 'TEMPORARIO', 'Temporário'
    ESTAGIARIO = 'ESTAGIARIO', 'Estagiário'
    VOLUNTARIO = 'VOLUNTARIO', 'Voluntário'
    DIARISTA = 'DIARISTA', 'Diarista'
    OUTRO = 'OUTRO', 'Outro'


# Modelo para Vagas
class Vaga(models.Model):
    titulo = models.CharField(max_length=255)
    localizacao = models.CharField(max_length=255)
    tipo = models.CharField(max_length=50, choices=TipoVaga.choices)
    descricao = models.TextField(null=False, blank=False)
    organizacao = models.CharField(max_length=255)
    salario = models.CharField(max_length=255, null=True, blank=True)
    logo = models.ImageField(upload_to='logos/', null=True, blank=True)
    usuario = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    criado_em = models.DateTimeField(default=timezone.now)
    atualizado_em = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.titulo

jobs/views.py
import os

from PIL import Image
from django.conf import settings
from django.contrib import messages
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

from usuarios.models import Perfil
from .models import Vaga, TipoVaga


def home(request):
    return render(request, 'jobs/home.html')


def api_listar_vagas(request):
    query = request.GET.get('q')
    if query:
        vagas = Vaga.objects.filter(titulo__icontains=query).order_by('criado_em').reverse().values(
            'id',
            'titulo',
            'localizacao',
            'tipo',
            'localizacao',
            'descricao',
            'organizacao',
            'salario',
            'logo',
            'criado_em',
        )
    else:
        vagas = Vaga.objects.all().order_by('criado_em').reverse().values(
            'id',
            'titulo',
            'localizacao',
            'tipo',
            'localizacao',
            'descricao',
            'organizacao',
            'salario',
            'logo',
            'criado_em',
        )
    return JsonResponse(list(vagas), safe=False)


def publicar_vaga(request):
    if not request.user.is_authenticated:
        return redirect(f"{reverse('usuarios:login')}?next={request.path}")

    # Verifica se o usuário tem um perfil e se é do tipo 'EMPRESA'
    try:
        perfil_usuario = Perfil.objects.get(usuario=request.user)
        if perfil_usuario.tipo != 'EMPRESA':
            messages.error(request, 'Apenas empresas podem publicar vagas.')
            return redirect('jobs:home')
    except Perfil.DoesNotExist:
        messages.error(request, 'Perfil não encontrado.')
        return redirect('usuarios:registrar')

    if request.method == 'POST':
        titulo = request.POST.get('titulo')
        localizacao = request.POST.get('localizacao')
        tipo = request.POST.get('tipo')
        descricao = request.POST.get('descricao')
        organizacao = request.POST.get('organizacao')
        salario = request.POST.get('salario')
        logo = request.FILES.get('logo')

        vaga = Vaga(
            titulo=titulo,
            localizacao=localizacao,
            tipo=tipo,
            descricao=descricao,
            organizacao=organizacao,
            salario=salario,
            logo=logo,
            usuario=request.user
        )

        # Tratando o upload da logo
        logo = request.FILES.get('logo')
        if logo:
            fs = FileSystemStorage()
            filename = fs.save(logo.name, logo)
            vaga.logo = fs.url(filename)

        vaga.save()

        messages.success(request, 'Vaga criada com sucesso!')
        return redirect('jobs:editar_vaga', vaga.id)
    return render(request, 'jobs/publicar_vaga.html', {'tipo_vaga_choices': TipoVaga.choices, })


def editar_vaga(request, vaga_id):
    if not request.user.is_authenticated:
        return redirect(f"{reverse('usuarios:login')}?next={request.path}")

    # Verifica se o usuário tem um perfil e se é do tipo 'EMPRESA'
    try:
        perfil_usuario = Perfil.objects.get(usuario=request.user)
        if perfil_usuario.tipo != 'EMPRESA':
            messages.error(request, 'Apenas empresas podem publicar vagas.')
            return redirect('jobs:home')
    except Perfil.DoesNotExist:
        messages.error(request, 'Perfil não encontrado.')
        return redirect('usuarios:registrar')

    vaga = get_object_or_404(Vaga, pk=vaga_id, usuario=request.user)

    if request.method == 'POST':
        vaga.titulo = request.POST.get('titulo')
        vaga.localizacao = request.POST.get('localizacao')
        vaga.tipo = request.POST.get('tipo')
        vaga.descricao = request.POST.get('descricao')
        vaga.organizacao = request.POST.get('organizacao')
        vaga.salario = request.POST.get('salario')

        # Tratando o upload da logo
        logo = request.FILES.get('logo')
        if logo:
            fs = FileSystemStorage()
            filename = fs.save(logo.name, logo)
            vaga.logo = fs.url(filename)

        vaga.save()

        # Atualizar tags aqui, se necessário

        messages.success(request, 'Vaga atualizada com sucesso!')
        return redirect('jobs:editar_vaga', vaga.id)

    return render(request, 'jobs/editar_vaga.html', {
        'vaga': vaga,
        'tipo_vaga_choices': TipoVaga.choices,
    })


def minhas_vagas(request):
    if not request.user.is_authenticated:
        return redirect(f"{reverse('usuarios:login')}?next={request.path}")

    # Verifica se o usuário tem um perfil e se é do tipo 'EMPRESA'
    try:
        perfil_usuario = Perfil.objects.get(usuario=request.user)
        if perfil_usuario.tipo != 'EMPRESA':
            messages.error(request, 'Apenas empresas podem publicar vagas.')
            return redirect('jobs:home')
    except Perfil.DoesNotExist:
        messages.error(request, 'Perfil não encontrado.')
        return redirect('usuarios:registrar')

    vagas = Vaga.objects.filter(usuario=request.user).order_by('criado_em').reverse()

    return render(request, 'jobs/vagas.html', {
        'vagas': vagas,
    })


def vaga(request, vaga_id):
    vaga = get_object_or_404(Vaga, pk=vaga_id)
    return render(request, 'jobs/vaga.html', {
        'vaga': vaga,
    })


def vaga_pdf(request, vaga_id):
    vaga = get_object_or_404(Vaga, pk=vaga_id)

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="{vaga.titulo}.pdf"'

    p = canvas.Canvas(response, pagesize=letter)
    width, height = letter

    margem_topo = 3 / 2.54 * 72
    altura_inicial = height - margem_topo

    # Adicionando o logo da empresa ou o logo padrão
    if vaga.logo:
        logo_path = os.path.join(settings.MEDIA_ROOT, vaga.logo.name)
    else:
        logo_path = os.path.join(settings.MEDIA_ROOT, 'logos/sem-logo.png')

    try:
        image = Image.open(logo_path)
        # Reduza o tamanho se necessário e ajuste a posição
        p.drawInlineImage(image, 40, altura_inicial - 40, width=80, height=80)
    except Exception as e:
        print("Erro ao carregar a imagem: ", e)

    # Adicionando o nome da empresa
    p.setFont("Helvetica-Bold", 24)
    p.drawString(40, altura_inicial - 80, str(vaga.usuario.perfil))

    # Adicionando o título da vaga
    p.setFont("Helvetica-Bold", 18)
    p.drawString(40, height - 190, vaga.titulo)

    # Adicionando mais detalhes da vaga
    p.setFont("Helvetica", 12)
    p.drawString(40, height - 220, f"Organização: {vaga.organizacao}")
    p.drawString(40, height - 240, f"Localização: {vaga.localizacao}")
    p.drawString(40, height - 260, f"Tipo: {vaga.get_tipo_display()}")
    p.drawString(40, height - 280, f"Publicado em: {vaga.criado_em.strftime('%d/%m/%Y')}")
    p.drawString(40, height - 300, f"Atualizado em: {vaga.atualizado_em.strftime('%d/%m/%Y')}")

    if vaga.salario:
        p.drawString(40, height - 340, f"Salário: {vaga.salario}")

    # Adicionando a descrição da vaga
    p.drawString(40, height - 360, "Descrição da Vaga:")
    textobject = p.beginText(40, height - 380)
    textobject.textLines(vaga.descricao)
    p.drawText(textobject)

    p.showPage()
    p.save()
    return response

jobs/templates/jobs/animationWorker-js.html
<script>
        const texts = ['django', 'python', 'ifro', 'professor', 'analista', 'fullstack', 'viagem', 'engenharia']
        const input = document.querySelector('#searchbox')
        const animationWorker = function (input, texts) {
            this.input = input
            this.defaultPlaceholder = this.input.getAttribute('placeholder')
            this.texts = texts
            this.curTextNum = 0
            this.curPlaceholder = ''
            this.blinkCounter = 0
            this.animationFrameId = 0
            this.animationActive = false
            this.input.setAttribute('placeholder', this.curPlaceholder)

            this.switch = (timeout) => {
                this.input.classList.add('imitatefocus')
                setTimeout(() => {
                    this.input.classList.remove('imitatefocus')
                    if (this.curTextNum === 0) this.input.setAttribute('placeholder', this.defaultPlaceholder)
                    else this.input.setAttribute('placeholder', this.curPlaceholder)

                    setTimeout(() => {
                        this.input.setAttribute('placeholder', this.curPlaceholder)
                        if (this.animationActive) this.animationFrameId = window.requestAnimationFrame(this.animate)
                    }, timeout)
                }, timeout)
            }

            this.animate = () => {
                if (!this.animationActive) return
                let curPlaceholderFullText = this.texts[this.curTextNum]
                let timeout = 400
                if (this.curPlaceholder === curPlaceholderFullText + '|' && this.blinkCounter === 3) {
                    this.blinkCounter = 0
                    this.curTextNum = this.curTextNum >= this.texts.length - 1 ? 0 : this.curTextNum + 1
                    this.curPlaceholder = '|'
                    this.switch(1000)
                    return
                } else if (this.curPlaceholder === curPlaceholderFullText + '|' && this.blinkCounter < 3) {
                    this.curPlaceholder = curPlaceholderFullText
                    this.blinkCounter++
                } else if (this.curPlaceholder === curPlaceholderFullText && this.blinkCounter < 3) {
                    this.curPlaceholder = this.curPlaceholder + '|'
                } else {
                    this.curPlaceholder =
                        curPlaceholderFullText
                            .split('')
                            .slice(0, this.curPlaceholder.length + 1)
                            .join('') + '|'
                    timeout = 200
                }
                this.input.setAttribute('placeholder', this.curPlaceholder)
                setTimeout(() => {
                    if (this.animationActive) this.animationFrameId = window.requestAnimationFrame(this.animate)
                }, timeout)
            }

            this.stop = () => {
                this.animationActive = false
                window.cancelAnimationFrame(this.animationFrameId)
            }

            this.start = () => {
                this.animationActive = true
                this.animationFrameId = window.requestAnimationFrame(this.animate)
                return this
            }
        }

        document.addEventListener('DOMContentLoaded', () => {
            let aw = new animationWorker(input, texts).start()
            input.addEventListener('focus', (e) => aw.stop())
            input.addEventListener('blur', (e) => {
                aw = new animationWorker(input, texts)
                if (e.target.value === '') setTimeout(aw.start, 2000)
            })
        })
    </script>

jobs/templates/jobs/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR" data-theme="light">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}

      {% endblock %} | JobZoom
    </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
    <link rel="stylesheet" href="{% static 'css/app.min.css' %}" />

    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js" defer></script>
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
    <script src="{% static 'js/app.js' %}" defer></script>
  </head>
  <body class="bg-slate-100">
    <div class="flex flex-col min-h-screen">
      <div>
        {% include 'jobs/navbar.html' %}
        <section class="max-w-7xl mx-auto pt-6">
          <h1 class="text-5xl font-semibold text-center text-slate-900">Ampliando Horizontes de Carreira para Todos</h1>
          <p class="max-w-2xl mx-auto text-center py-6 text-slate-700 font-light">
            "Desde que comecei a usar o JobZoom, a busca por emprego se tornou surpreendentemente simples. Recomendo fortemente para quem busca eficiência e ótimas vagas!" &mdash; <strong>João da Silva</strong>
          </p>
        </section>

        <!-- Carrossel Container -->
        <div class="swiper mySwiper max-w-4xl mx-auto mb-24">
          <!-- Slides Wrapper -->
          <div class="swiper-wrapper flex justify-between items-center py-4">
            <!-- Slides -->
            <div class="swiper-slide">
              <img class="h-10" src="/media/logos/autospeed.png" alt="autospeed" />
            </div>
            <div class="swiper-slide">
              <img class="h-10" src="/media/logos/fakery.png" alt="fakery" />
            </div>
            <div class="swiper-slide">
              <img class="h-10" src="/media/logos/redpepper.png" alt="redpepper" />
            </div>
            <div class="swiper-slide">
              <img class="h-10" src="/media/logos/roadlogic.png" alt="roadlogic" />
            </div>
            <div class="swiper-slide">
              <img class="h-10" src="/media/logos/fakery.png" alt="fakery" />
            </div>
            <div class="swiper-slide">
              <img class="h-10" src="/media/logos/spacecube.png" alt="spacecube" />
            </div>
          </div>
        </div>

        <script>
          window.onload = function () {
            const swiper = new Swiper('.mySwiper', {
              // Opções do Swiper
              speed: 1500, // Velocidade da transição de slides
              slidesPerView: 5, // Quantidade de slides por visualização
              loop: true, // Ativa o loop infinito
              autoplay: {
                delay: 2500
              }
              // Adicione outras configurações que desejar
            })
          }
        </script>
      </div>
      <main class="flex-grow bg-stone-50 pb-12">
        {% block content %}

        {% endblock %}
      </main>
      {% include 'jobs/footer.html' %}
    </div>

  </body>
</html>

jobs/templates/jobs/editar_vaga.html
{% extends 'jobs/base.html' %}
{% load static %}

{% block title %}
    Altear vaga
{% endblock %}Publicar uma vaga{% block content %}
    <div class="max-w-3xl mx-auto px-6 py-12 mt-12 shadow">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="space-y-12">
                <div>
                    <h2 class="text-2xl font-semibold leading-7 text-gray-900">Alterar informações da vaga Vaga</h2>
                    <p class="mt-1 text-sm leading-6 text-gray-600">Preencha os campos abaixo para atualizar a vaga.</p>

                    <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
                        <div class="col-span-full">
                            <label for="titulo" class="block text-sm font-medium leading-6 text-gray-900">Título da
                                Vaga</label>
                            <div class="mt-2">
                                <input type="text" name="titulo" id="titulo" value="{{ vaga.titulo }}"
                                       autocomplete="titulo"
                                       class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"/>
                            </div>
                            <small class="text-slate-400 font-light">Exemplo: "Desenvolvedor Django Senior",
                                "Engenheiro", "Programador Python Junior"</small>
                        </div>

                        <div class="col-span-full">
                            <label for="localizacao" class="block text-sm font-medium leading-6 text-gray-900">Local de
                                Trabalho</label>
                            <div class="mt-2">
                                <input type="text" name="localizacao" id="localizacao" value="{{ vaga.localizacao }}"
                                       autocomplete="localizacao"
                                       class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"/>
                            </div>
                            <small class="text-slate-400 font-light">Exemplo: "Remoto", "Remoto/Brasil",
                                "Ariquemes"</small>
                        </div>

                        <div class="sm:col-span-3">
                            <label for="tipo" class="block text-sm font-medium leading-6 text-gray-900">Tipo de
                                Emprego</label>
                            <div class="mt-2">
                                <select id="tipo" name="tipo" autocomplete="tipo"
                                        class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:max-w-xs sm:text-sm sm:leading-6">
                                    {% for choice in tipo_vaga_choices %}
                                        <option value="{{ choice.0 }}"
                                                {% if vaga.tipo == choice.0 %}selected{% endif %}>
                                            {{ choice.1 }}
                                        </option>
                                    {% endfor %}
                                </select>

                            </div>
                        </div>

                        <div class="col-span-full">
                            <label for="descricao" class="block text-sm font-medium leading-6 text-gray-900">Descrição
                                Da Vaga</label>
                            <div class="mt-2">
                                <textarea id="descricao" name="descricao" rows="3"
                                          class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6">{{ vaga.descricao|default_if_none:"" }}</textarea>
                            </div>
                            <p class="mt-3 text-sm leading-6 text-gray-600">Descrição da vaga, requisitos, benefícios,
                                etc.</p>
                        </div>


                        <div class="col-span-full">
                            <label for="organizacao" class="block text-sm font-medium leading-6 text-gray-900">Nome Da
                                Empresa</label>
                            <div class="mt-2">
                                <input type="text" name="organizacao" id="organizacao" value="{{ vaga.organizacao }}"
                                       autocomplete="organizacao"
                                       class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"/>
                            </div>
                        </div>

                        <div class="col-span-full">
                            <label for="salario" class="block text-sm font-medium leading-6 text-gray-900">Salário
                                (opcional)</label>
                            <div class="mt-2">
                                <input type="text" name="salario" id="salario" value="{{ vaga.salario }}"
                                       autocomplete="salario"
                                       class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"/>
                            </div>
                            <small class="text-slate-400 font-light">Exemplo: "R$5000,00", "$70,000 - $120,000",
                                "€80,000 — €102,000"</small>
                        </div>

                        <div class="col-span-full">
                            <label for="logo" class="block text-sm font-medium leading-6 text-gray-900">Logo Da Empresa
                                <div class="mt-2 flex items-center gap-x-3">
                                    {% if vaga.logo %}
                                        <img src="{{ vaga.logo }}" alt="Logo da empresa"
                                             class="w-16 h-16 rounded-md shadow-sm"/>
                                    {% else %}
                                        <img src="{% get_media_prefix %}/logos/sem-logo.png" alt="Logo da empresa"
                                             class="w-16 h-16 rounded-md shadow-sm"/>
                                    {% endif %}
                                    <input type="file" name="logo" id="logo" autocomplete="logo" class="sr-only"/>
                                    <button type="button"
                                            class="rounded-md bg-white px-2.5 py-1.5 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50">
                                        Escolher
                                    </button>
                                </div>
                            </label>
                            <small class="text-slate-400 font-light">130x130 é melhor, mas qualquer tamanho
                                funciona</small>
                        </div>

                    </div>
                </div>

            </div>

            <div class="mt-6 flex items-center justify-end gap-x-6">
                <button type="button" class="text-sm font-semibold leading-6 text-gray-900">Cancelar</button>
                <button type="submit"
                        class="rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
                    Publicar
                </button>
            </div>
        </form>
    </div>

{% endblock %}

jobs/templates/jobs/footer.html
<footer class="w-full bg-slate-200/25">

    <div class="max-w-4xl mx-auto flex flex-col items-center gap-3 py-12">
        <div class="text-slate-500 text-lg tracking-wide font-light"><strong class="text-accent">JobZoom</strong> - Ativididade para a Disciplina de Programação IV - 2023/2</div>
        <div class="font-semibold text-slate-700">Aluno: Lucas Pedreira Vital - IFRO Campus Ariquemes</div>
        <div class="font-semibold text-slate-700">Professor: Marcos Alves Faino</div>
        <div class="text-slate-500 text-sm tracking-wide font-light">&copy; 2023</div>
    </div>

</footer>

jobs/templates/jobs/navbar.html
<header>
    <nav class="max-w-7xl mx-auto flex justify-between items-center p-12">
        <ul>
            <li>
                <a href="{% url "jobs:home" %}" class="text-3xl font-bold text-accent">JobZoom</a>
            </li>
        </ul>
        <ul class="flex items-center space-x-6">
            <li><a class="font-semibold text-lg hover:underline text-slate-900" href="{% url 'jobs:minhas_vagas' %}">Minhas vagas</a></li>
            {% if request.user.is_authenticated %}
                <li>
                    <a class="font-semibold text-lg hover:underline text-slate-900" href="{% url 'usuarios:logout' %}">Sair</a>
                </li>
            {% else %}
                <li>
                    <a class="font-semibold text-lg hover:underline text-slate-900" href="{% url 'usuarios:login' %}">Login</a>
                </li>
                <li>
                    <a class="font-semibold text-lg hover:underline text-slate-900"
                       href="{% url 'usuarios:registrar' %}">Registrar</a>
                </li>

            {% endif %}
        </ul>
        <ul class="flex space-x-4 text-slate-700">
            {% if request.user.is_authenticated %}
                <li>
                    Olá, <span>{{ user.get_username }}</span>
                </li>
            {% endif %}
            <li><a href="{% url "jobs:publicar_vaga" %}" role="button" class="btn-primary">Publicar uma Vaga</a></li>
        </ul>
    </nav>
</header>

jobs/templates/jobs/vaga.html
{% extends 'jobs/base.html' %}
{% load static %}

{% block title %}
    Início
{% endblock %}
{% block content %}



    <article class="max-w-4xl mx-auto mt-10 p-6 bg-white shadow-lg rounded-lg">
        <div class="flex flex-col">
            <div class="flex items-center space-x-2  p-4">
                <div>
                    {% if vaga.logo %}
                        <img src="{{ vaga.logo }}" alt="" class="w-14 h-14 object-contain rounded-lg"/>
                    {% else %}
                        <img src="{% get_media_prefix %}logos/sem-logo.png" alt=""
                             class="w-14 h-14 object-contain rounded-lg"/>
                    {% endif %}
                </div>
                <div>
                    <h1 class="text-2xl font-bold text-accent">{{ vaga.usuario.perfil }}</h1>
                </div>
            </div>

            <div class="sm:w-3/4 p-4">
                <h2 class="text-2xl font-bold text-gray-800">{{ vaga.titulo }}</h2>
                <p class="text-gray-600 mt-2">{{ vaga.organizacao }}</p>
                <p class="mt-1 text-gray-500">Localização: {{ vaga.localizacao }}</p>
                <p class="mt-1 text-gray-500">Tipo: {{ vaga.get_tipo_display }}</p>
                <p class="mt-1 text-gray-500">Publicado em: {{ vaga.criado_em|date:"d/m/Y" }}</p>
                <p class="mt-1 text-gray-500">Atualizado em: {{ vaga.atualizado_em|date:"d/m/Y" }}</p>
                {% if vaga.salario %}
                    <p class="mt-1 text-gray-500">Salário: {{ vaga.salario }}</p>
                {% endif %}
            </div>

        </div>

        <div class="mt-4 p-4">
            <h3 class="text-xl font-semibold text-gray-800">Descrição da Vaga</h3>
            <p class="mt-2 text-gray-600">{{ vaga.descricao }}</p>
        </div>

        <div class="mt-4 p-4">
            <a href="{% url 'jobs:vaga_pdf' vaga.id %}"
               class="bg-accent hover:bg-accent-hover text-white font-bold py-2 px-4 rounded inline-flex space-x-2">
                <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true"
                     xmlns="http://www.w3.org/2000/svg"
                     fill="none" viewBox="0 0 16 20">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                          d="M1 18a.969.969 0 0 0 .933 1h12.134A.97.97 0 0 0 15 18M1 7V5.828a2 2 0 0 1 .586-1.414l2.828-2.828A2 2 0 0 1 5.828 1h8.239A.97.97 0 0 1 15 2v5M6 1v4a1 1 0 0 1-1 1H1m0 9v-5h1.5a1.5 1.5 0 1 1 0 3H1m12 2v-5h2m-2 3h2m-8-3v5h1.375A1.626 1.626 0 0 0 10 13.375v-1.75A1.626 1.626 0 0 0 8.375 10H7Z"></path>
                </svg>
                <span>Gerar PDF</span>
            </a>
        </div>

    </article>




{% endblock %}